name: Deploy
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    environment: prod
    steps:
        - uses: actions/checkout@v1

        - name: Install dependencies
          run: npm install

        - name: Build
          run: npm run build

        - name: S3/CloudFront Deploy
          uses: staevs/s3-deploy-action@v1.2.4
          if: success()
          with:
            args: --follow-symlinks --delete --no-progress
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
            AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_DIST_ID }}
            S3_SOURCE_DIR: 'dist'